version: '3.7'

services:

  t1_producer:
    build: ./t1_producer
    environment:
      KAFKA_BROKER_URL: broker:9092
      KEY_METRICS_TOPIC: queueing.key-metrics
      TRANSACTIONS_PER_SECOND: 1000

  t1_loader:
    build: ./t1_loader
    environment:
      KAFKA_BROKER_URL: broker:9092
      KEY_METRICS_TOPIC: queueing.key-metrics
      T1_LOAD_TOPIC: queueing.km-load

  flask:
    build:
      context: ./web_app/api
      dockerfile: Dockerfile
    volumes:
      - './web_app/api:/usr/src/app'
    ports:
      - 5001:5000
    environment:
      - ENV_CONFIG=dev
      - DATABASE_URL=postgres://postgres:postgres@db:5432/dss_db_dev

networks:
  default:
    external:
      name: kafka-network
